# -*- mode: ruby -*-
# vi: set ft=ruby :

hostname = "tomcat9-test01"

Vagrant.configure("2") do |config|

  config.vm.box      = "generic/ubuntu2004"
  config.vm.hostname = hostname
  config.vm.network "private_network", ip: "192.168.58.88"

  config.vm.provider "virtualbox" do |v|
    v.name   = hostname
    v.memory = 1024
    v.cpus   = 1

    ## change vga controller default(VBoxVGA) to VMSVGA
    ## virtualbox says that "Invalid settings detected"
    v.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
  end

  config.vm.provision "ansible" do |ansible|
    ansible.config_file = "../../../../ansible.cfg"
    ansible.playbook    = "tomcat90-test.yml"
  end

  config.vbguest.auto_update = false
end
