---
- name: "test | apt curl (latest)"
  apt:
    pkg:
      - curl
    update_cache: yes
    state: latest
    install_recommends: yes ## for libtcnative-1(apr library)
  become: yes
  tags:
    - test

- name: "test | http://{{ domain }}{{ test.path }}"
  shell: "curl http://{{ domain }}:{{ conf.Service.Connector_http._attr.port }}{{ test.path }} --resolve {{ domain }}:{{ conf.Service.Connector_http._attr.port }}:127.0.0.1  -w '%{http_code}' -o /dev/null -s"
  register: result
  args:
    warn: false
  retries: 30
  delay: 1
  until: result.stdout == "200" ## right operand must be treated as string
  when:
    - http_server == "enable"
  tags:
    - test

- name: "test | https://{{ domain }}{{ test.path }}"
  shell: "curl https://{{ domain }}:{{ conf.Service.Connector_https._attr.port }}{{ test.path }} --resolve {{ domain }}:{{ conf.Service.Connector_https._attr.port }}:127.0.0.1  -w '%{http_code}' -o /dev/null -s"
  register: result
  args:
    warn: false
  retries: 30
  delay: 1
  until: result.stdout == "200" ## right operand must be treated as string
  when:
    - https_server == "enable"
  tags:
    - test
